# Generated by Django 3.0.14 on 2022-03-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('nif', models.CharField(max_length=9, verbose_name='NIF')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=9, verbose_name='Teléfono')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha de expiración')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('nif', models.CharField(max_length=9, verbose_name='NIF')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Desfibrillator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('location', models.CharField(max_length=255, verbose_name='Localización')),
                ('installation_date', models.DateTimeField()),
                ('battery_expiration_date', models.DateTimeField()),
                ('check_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desfibrillator', to='reports.Client')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desfibrillator', to='reports.Patch')),
                ('professional', models.ManyToManyField(related_name='desfibrillator', to='reports.Professional')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.Company'),
        ),
    ]
