# Generated by Django 3.2 on 2022-03-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defibrillator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('location', models.CharField(max_length=255, verbose_name='Localización')),
                ('installation_date', models.DateTimeField()),
                ('battery_expiration_date', models.DateTimeField()),
                ('check_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defibrillator', to='reports.client')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defibrillator', to='reports.patch')),
                ('professional', models.ManyToManyField(related_name='defibrillator', to='reports.Professional')),
            ],
        ),
        migrations.DeleteModel(
            name='Desfibrillator',
        ),
    ]
