# Generated by Django 3.2 on 2022-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20220321_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defibrillator',
            name='professional',
            field=models.ManyToManyField(related_name='defibrillator', to='reports.Professional'),
        ),
    ]
