# Generated by Django 3.2 on 2022-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_defibrillator_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defibrillator',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='professional',
            field=models.ManyToManyField(null=True, related_name='defibrillator', to='reports.Professional'),
        ),
    ]
