# Generated by Django 3.2 on 2022-03-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20220321_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defibrillator',
            name='battery_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='patch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='defibrillator', to='reports.patch'),
        ),
        migrations.AlterField(
            model_name='defibrillator',
            name='professional',
            field=models.ManyToManyField(blank=True, related_name='defibrillator', to='reports.Professional'),
        ),
    ]
