# Generated by Django 3.2 on 2022-03-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20220321_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='941XXXYYY', max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='941XXXYYY', max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phone',
            field=models.CharField(default='941XXXYYY', max_length=9, verbose_name='Teléfono'),
        ),
    ]
