# Generated by Django 3.2 on 2022-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20220322_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='defibrillator',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitud'),
        ),
    ]
