# Generated by Django 3.2 on 2022-03-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20220322_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defibrillator',
            name='patch',
        ),
        migrations.AddField(
            model_name='patch',
            name='defibrillator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch', to='reports.defibrillator'),
        ),
    ]
