# Generated by Django 3.2 on 2022-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20220330_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
