# Generated by Django 3.2 on 2022-04-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20220331_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defibrillator',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defibrillator', to='reports.client'),
        ),
    ]
