# Generated by Django 3.2 on 2022-04-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_defibrillator_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defibrillator',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='defibrillator', to='reports.client'),
        ),
    ]
